Bolao.App={
 init(){this.el=document.querySelector('#content');document.querySelector('#login-form').onsubmit=e=>this.handleLogin(e);document.querySelector('#register-btn').onclick=()=>this.showPublicView('register-view');document.querySelector('#forgot-btn').onclick=()=>{document.querySelector('#reset-email').value=document.querySelector('#email').value;this.showPublicView('reset-view')};document.querySelector('#back-login-btn').onclick=()=>this.showPublicView('auth-view');document.querySelector('#back-reset-btn').onclick=()=>this.showPublicView('auth-view');document.querySelector('#register-form').onsubmit=e=>this.handleRegister(e);document.querySelector('#reset-form').onsubmit=e=>this.handleReset(e);document.querySelector('#logout-btn').onclick=()=>Bolao.Auth.logout();document.querySelector('#menu-btn').onclick=()=>document.querySelector('aside').classList.toggle('open');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>this.navigate(b.dataset.page));Bolao.Auth.init()},
 showPublicView(id){['auth-view','register-view','reset-view'].forEach(x=>document.querySelector('#'+x).classList.toggle('hidden',x!==id));document.querySelector('#app').classList.add('hidden')},
 showAuth(){this.showPublicView('auth-view')},
 async handleLogin(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{await Bolao.Auth.login(document.querySelector('#email').value,document.querySelector('#password').value)}catch(x){this.toast(this.authMessage(x))}finally{b.disabled=false}},
 async handleRegister(e){e.preventDefault();const name=document.querySelector('#register-name').value,email=document.querySelector('#register-email').value,password=document.querySelector('#register-password').value,confirm=document.querySelector('#register-confirm').value,b=e.submitter;if(password!==confirm)return this.toast('A confirmação da senha não confere');b.disabled=true;try{await Bolao.Auth.register(name,email,password);e.target.reset();this.toast('Conta criada com sucesso')}catch(x){this.toast(this.authMessage(x))}finally{b.disabled=false}},
 async handleReset(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{await Bolao.Auth.resetPassword(document.querySelector('#reset-email').value);this.toast('Se o e-mail estiver cadastrado, o link de recuperação será enviado.');setTimeout(()=>this.showPublicView('auth-view'),1200)}catch(x){this.toast(this.authMessage(x))}finally{b.disabled=false}},
 authMessage(x){const map={'auth/email-already-in-use':'Este e-mail já está cadastrado','auth/invalid-email':'Informe um e-mail válido','auth/weak-password':'A senha deve ter pelo menos 6 caracteres','auth/user-not-found':'E-mail ou senha inválidos','auth/wrong-password':'E-mail ou senha inválidos','auth/invalid-credential':'E-mail ou senha inválidos','auth/too-many-requests':'Muitas tentativas. Aguarde e tente novamente'};return map[x.code]||x.message||'Não foi possível concluir a operação'},
 enter(u){['auth-view','register-view','reset-view'].forEach(x=>document.querySelector('#'+x).classList.add('hidden'));document.querySelector('#app').classList.remove('hidden');document.querySelector('#user-name').textContent=u.name;document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',u.role!=='admin'));this.navigate('dashboard')},
 navigate(p){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.querySelector('aside').classList.remove('open');const m={dashboard:[Bolao.Dashboard,'render'],weekly:[Bolao.Predictions,'weekly'],preseason:[Bolao.Predictions,'preseason'],ranking:[Bolao.Ranking,'render'],regulation:[Bolao.Regulation,'render'],profile:[Bolao.Profile,'render'],admin:[Bolao.Admin,'render']};const[o,f]=m[p]||m.dashboard;o[f]()},
 content(h){this.el.innerHTML=h;scrollTo(0,0)},
 toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
};window.addEventListener('DOMContentLoaded',()=>Bolao.App.init());