Bolao.Auth={
 user:null,
 cleanName(value){return String(value||'').trim().replace(/\s+/g,' ').slice(0,40)},
 async init(){const c=BOLAO_CONFIG.firebase;if(c.apiKey==='COLE_AQUI'){Bolao.App.toast('Preserve seu firebase-config.js atual antes de publicar');return Bolao.App.showAuth()}firebase.initializeApp(c);Bolao.db=firebase.firestore();Bolao.fbAuth=firebase.auth();Bolao.fbAuth.onAuthStateChanged(async u=>{if(!u){this.user=null;return Bolao.App.showAuth()}try{const ref=Bolao.db.collection('users').doc(u.uid);let d=await ref.get();if(!d.exists){await ref.set({email:u.email,name:u.displayName||u.email.split('@')[0],role:'player',active:true,paid:false,createdAt:firebase.firestore.FieldValue.serverTimestamp()});d=await ref.get()}const x=d.data();this.user={uid:u.uid,email:u.email,name:x.name||u.displayName||u.email.split('@')[0],role:x.role||'player',active:x.active!==false,paid:x.paid===true,emailVerified:u.emailVerified};Bolao.App.enter(this.user)}catch(e){Bolao.App.toast('Erro ao carregar perfil: '+e.message)}})},
 login(email,password){return Bolao.fbAuth.signInWithEmailAndPassword(email.trim(),password)},
 async register(name,email,password){const clean=this.cleanName(name);if(clean.length<2)throw Error('Informe um nome com pelo menos 2 caracteres.');const r=await Bolao.fbAuth.createUserWithEmailAndPassword(email.trim(),password);try{await r.user.updateProfile({displayName:clean});await Bolao.db.collection('users').doc(r.user.uid).set({email:r.user.email,name:clean,role:'player',active:true,paid:false,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});this.user={uid:r.user.uid,email:r.user.email,name:clean,role:'player',active:true,paid:false,emailVerified:r.user.emailVerified};return r}catch(e){try{await r.user.delete()}catch(_){}throw e}},
 resetPassword(email){return Bolao.fbAuth.sendPasswordResetEmail(email.trim())},
 async updateName(name){const clean=this.cleanName(name);if(clean.length<2)throw Error('Informe um nome com pelo menos 2 caracteres.');const u=Bolao.fbAuth.currentUser;if(!u)throw Error('Sessão expirada. Entre novamente.');await Bolao.db.collection('users').doc(u.uid).update({name:clean,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await u.updateProfile({displayName:clean});this.user.name=clean;document.querySelector('#user-name').textContent=clean;return clean},
 async updatePassword(currentPassword,newPassword){const u=Bolao.fbAuth.currentUser;if(!u)throw Error('Sessão expirada. Entre novamente.');const credential=firebase.auth.EmailAuthProvider.credential(u.email,currentPassword);await u.reauthenticateWithCredential(credential);await u.updatePassword(newPassword)},
 logout(){return Bolao.fbAuth.signOut()}
};